spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      port: 27018
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}   

redis:
  host: localhost
  port: 6379

domain:
  name: localhost