spring:
  data:
    mongodb:
      host: mongo11
      database: bdc
      username: root
      password: root
    redis:
      port: 6379
      host: redis1
  elasticsearch:
    uris: http://host.docker.internal:9200

domain:
  name: localhost

base:
  url: http://localhost