spring:
  data:
    mongodb:
      database: bdc
      host: mongo
      username: root
      password: root
    redis:
      port: 6379
      host: redis
  elasticsearch:
    uris: http://es:9200

server:
  base_url: http://localhost
  servlet:
    session:
      cookie:
        domain: localhost

base:
  url: http://localhost

fe_base_url: ${server.base_url}:5173