spring:
  data:
    mongodb:
      database: "bdc"
      port: 27018
      username: "nthanh"
      password: "123456"
    redis:
      port: 6379
      host: localhost
  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    org:
      elasticsearch:
        client: TRACE

server:
  base_url: http://localhost
  servlet:
    session:
      cookie:
        domain: localhost

base:
  url: http://localhost

fe_base_url: ${server.base_url}:5173